### ISSUE TITLE
faster message sending by running as a daemon in background?

### ISSUE THREAD

**Issue by egabosh** [8go/matrix-commander#180]
Moin,

I'm using matrix-commander via docker on a Pi4.
I send messages via:
```
docker compose run -T name -m "$message" -k --room $room
```
Image: matrixcommander/matrix-commander

Works fine but takes about 30 seconds to send a message on my Pi4.
Is there a way to let it run daemonized in the background for faster sending?

Thank you!

**Comment by 53c70r** [comment]
Try this and feed it with stdin:
`matrix-commander --code -m _`
It's blazing fast after all the keys ans stuff are in mem.

**Comment by egabosh** [comment]
Great Feature, thank you! Solved it with a fifo-pipe this way:
```
mkfifo somefilename
tail -F somefilename | docker compose run -T name -m _ -k --room $room
```
Send message (fast) with
```
echo "message" >somefilename
```
Newline seems to send the message.
Is there some way to send newlines in a message this way? Tried to use escape with '\n' but didnt't work.

**Comment by egabosh** [comment]
Solved it with HTML messages and <br> Tag. 
`echo "$matrix_message" | perl -pe 's/\n/<br>/' >namedpipe`

For reading the pipe in (backgrounded) docker (compose) container I use:
```
  matrix-commander-pipe:
    image: matrixcommander/matrix-commander
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./matrix-commander-data:/data:rw
      - /usr/local/share/pipe.fifo:/pipe.fifo
    entrypoint: /bin/bash -c 'cd /data && tail -F /pipe.fifo | /app/matrix_commander/matrix-commander -m _ --html --room myroom --log-level INFO INFO'
    restart: unless-stopped     
```
Maybe this helps somebody!
